# Generated by Django 4.1.7 on 2023-04-20 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_alter_category_options_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='name',
            field=models.CharField(default=False, max_length=255),
            preserve_default=False,
        ),
    ]
