# Generated by Django 4.1.7 on 2023-05-03 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_item_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='price',
            new_name='condition',
        ),
    ]
